//! `{{NAME}}` – {{DESCRIPTION}}
//!
//! Generated by `appctl new {{NAME}}`. Edit the Input/Output structs and the
//! body of `run` to implement the command; it is already registered (via the
//! `register_command!` at the bottom) and callable over the CLI and HTTP API.

use crate::commands::{Command, CommandError};
use crate::context::Ctx;
use crate::register_command;
use async_trait::async_trait;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(Default)]
pub struct {{STRUCT}};

/// Typed request body. Fields become CLI flags / JSON body keys and appear in
/// the auto-generated JSON Schema.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct {{STRUCT}}Input {
    /// TODO: describe this field.
    pub message: String,
}

/// Typed response. This is the bare body returned over HTTP.
#[derive(Debug, Serialize, JsonSchema)]
pub struct {{STRUCT}}Output {
    pub echoed: String,
}

#[async_trait]
impl Command for {{STRUCT}} {
    type Input = {{STRUCT}}Input;
    type Output = {{STRUCT}}Output;

    fn name(&self) -> &'static str {
        "{{NAME}}"
    }

    fn description(&self) -> &'static str {
        "{{DESCRIPTION}}"
    }

    async fn run(
        &self,
        input: {{STRUCT}}Input,
        _cx: &Ctx<'_>,
    ) -> Result<{{STRUCT}}Output, CommandError> {
        // TODO: implement. `_cx` exposes fs() and network() capabilities.
        Ok({{STRUCT}}Output {
            echoed: input.message,
        })
    }
}

register_command!({{STRUCT}});
